### ISSUE TITLE
Any ideas to release training codes?

### ISSUE THREAD

**Issue by Darrenxc** [h4nwei/SPAQ#1]
Hi, 
Congratulations on your work. Do you have a plan to release training codes?

**Comment by h4nwei** [comment]
> Hi,
> Congratulations on your work. Do you have a plan to release training codes?

Hi Darrenxc,
Thanks for your interest in our work. We are not going to release the training codes, since they are easy to reproduce based on the testing codes.

Best,
Hanwei
