### ISSUE TITLE
database is synthetic or real ?

### ISSUE THREAD

**Issue by DAVID-Hown** [h4nwei/SPAQ#12]
Hello, thank you for your work. I have a question about the data set.
As for the SPAQ data set proposed in the article, I would like to ask whether it belongs to the synthetic distortion data set or the real distortion data set. You're not very clear about the distinction, right?

**Comment by h4nwei** [comment]
> Hello, thank you for your work. I have a question about the data set.
> As for the SPAQ data set proposed in the article, I would like to ask whether it belongs to the synthetic distortion data set or the real distortion data set. You're not very clear about the distinction, right?

Hi @DAVID-Hown. The SPAQ  is a realistic distortion database, which has been made clear clarification in the manuscript.
