### ISSUE TITLE
A question about image process

### ISSUE THREAD

**Issue by gcbanana** [h4nwei/SPAQ#13]
During training, the images are first resized to 512 and then random cropped to $224*224*3$ OR resized to 256 then cropped to $224*224*3$?

**Comment by h4nwei** [comment]
> During training, the images are first resized to 512 and then random cropped to $224_224_3$ OR resized to 256 then cropped to $224_224_3$?
Hi@gcbanana,
Sorry for the later reply. We used the former strategy to train the models, and more details can be found in the manuscript.
