### ISSUE TITLE
Database Access

### ISSUE THREAD

**Issue by nicolasch96** [h4nwei/SPAQ#16]
Hello,

Your article is really interesting, and I would love to access the database. However, the download process is really complicated. You need to download Baidu and then create an account and it's all in Chinese, which is not convenient for non-Chinese speaking users or non-Baidu users (especially if you don't want to create random accounts).

Is it possible to put a link to a separate drive? like, google drive?

Thank you!

Best,

Nicolas

**Comment by h4nwei** [comment]
> Hello,
> 
> Your article is really interesting, and I would love to access the database. However, the download process is really complicated. You need to download Baidu and then create an account and it's all in Chinese, which is not convenient for non-Chinese speaking users or non-Baidu users (especially if you don't want to create random accounts).
> 
> Is it possible to put a link to a separate drive? like, google drive?
> 
> Thank you!
> 
> Best,
> 
> Nicolas

Dear Nicolas,

Thanks for your interest in our work. We also provide the [MEGA](https://mega.nz/folder/SYwUkKjC) download link ( password: SPaUCc-iWU1VvaZIqmUlnQ). I hope you enjoy the database . 

Best,
Hanwei
