### ISSUE TITLE
Scenes shot with many devices

### ISSUE THREAD

**Issue by nicolasch96** [h4nwei/SPAQ#17]
Hello,

In your paper, you mention that 1000 images were collected from different scenes shot with the same devices.

Is there a way to extract these scenes/images? 

I was thinking of using a clustering method but it can still result in bad clusters.

Thank you

Nicolas

**Comment by h4nwei** [comment]
Hi Nicolas,

Sorry. We do not attempt to extract these images for the task of image quality assessment.

Best,
Hanwei
