### ISSUE TITLE
the two value of "time" label in EXIF_tags mean what

### ISSUE THREAD

**Issue by xiaovea** [h4nwei/SPAQ#4]

**Comment by h4nwei** [comment]
Dear xiaovea @xiaovea ,

Exposure time is a circular variable, and we use the (Sin(2*pi*hour/24), Cos(2*pi*hour/24)) to encode. Hoping it helps.

Best, 
Hanwei

**Comment by xiaovea** [comment]
thanks for your reply

**Comment by h4nwei** [comment]
Typo: (Sin(2*pi*hour/24, Cos(2*pi*hour/24)) --> (Sin(2\*pi\*hour/24, Cos(2\*pi\*hour/24))
