### ISSUE TITLE
Output shape of network

### ISSUE THREAD

**Issue by KleinXin** [h4nwei/SPAQ#6]
In the demo code BL_demo.py

In line 68, score_1 = self.model(image_1).mean()

If the output of the model is a scalar which is the score of the image, why the mean value is calculated as the score of the image?

I use two images with shape 910x512 and 560x420, the shapes of output are 32 and 24

**Comment by h4nwei** [comment]
Dear   KleinXin@KleinXin

During testing, we crop 224*224*3 patches from a test image with a stride of 112. The final quality and attribute
scores are computed by averaging all patch predictions.

Best,
Hanwei

**Comment by KleinXin** [comment]
Thx!
After carefully reading the Prepare_image code, I realized that you cropped patches from the image.

Another question is that during the trainning, the same procedure is performed as well?

**Comment by h4nwei** [comment]
> Thx!
> After carefully reading the Prepare_image code, I realized that you cropped patches from the image.
> 
> Another question is that during the trainning, the same procedure is performed as well?

Hi KleinXin,

When we trained the network, we randomly crop 224*224*3 patches from an image.

**Comment by h4nwei** [comment]
Typo: 224*224*3 -> 224\*224\*3

**Comment by KleinXin** [comment]
Thx!
I will try to write the trainnning codes by myself.

**Comment by Twang1998** [comment]
@KleinXin could you please share the training codes with me? I tried to write training code but it couldn't reach the performance of the article.
