### ISSUE TITLE
BL_release.pt could not download.

### ISSUE THREAD

**Issue by eeric** [h4nwei/SPAQ#7]
please provide baidu link, thanks.

**Comment by h4nwei** [comment]
Dear eeric @eeric ,

Thanks for your interest in our research. The weights can be downloaded at https://pan.baidu.com/s/1TjHZPxBCLrrMdpLDpn8jPw (Code: d6n5). Hope it helps.

Best, 
Hanwei

**Comment by gonelove31** [comment]
Just tried https://baidufast.com/ and it actually works pretty well. They give  for free. Honestly, that’s pretty cheap compared to most of these services.
