### ISSUE TITLE
spaq database download

### ISSUE THREAD

**Issue by maoxiaofei99** [h4nwei/SPAQ#8]
Hello, I have read your great paper and  tried to download the spaq database to reproduce the experiment results, but as the baiduyun for SPAQ consists of only individual image files, it is difficult to download more than 10000 files at once. So , I would like to know whether it is possible for you to upload one or several zipped file of the database or just release a google drive link of the database ? As the download speed of MEGA free account is real show. 

Thanks in advance!

**Comment by h4nwei** [comment]
Hi @maoxiaofei99 

The zip file can be downloaded at https://pan.baidu.com/s/1JzwZxwSOpIqcc16cOliBVw (code: 8og5). Hope it helps.

Best, 
Hanwei

**Comment by sourav-paul** [comment]
Hi @h4nwei, any chance there is a download client-independent URL?

**Comment by h4nwei** [comment]
> Hi @h4nwei, any chance there is a download client-independent URL?

Hi @sourav-paul , thanks for your interest in our work. Sorry, we do not have a client-independent URL.
